### ISSUE TITLE
prj get coordinatesystem

### ISSUE THREAD

**Issue by sigster** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#89] opened 2024-09-18 13:06 UTC
Hi how cad I get coordinatesystem of a shapefile from prj file

**Comment by FObermaier** [comment] 2024-09-23 19:20
This project is deprecated, please use NetTopologySuite.IO.Esri instead.

**Comment by KubaSzostak** [comment] 2024-09-25 06:12
Closed as a duplicate of https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/issues/56

**Closed as completed by KubaSzostak** 2024-09-25 06:12 UTC
